name: Update website index
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@v2

    - run:
        python -m pip install --upgrade pip
    - run:
        pip install pycoingecko
    - run:
        pip install scipy

    - name: Update index
      run:  python main.py

    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Daily update
